### PR TITLE
TEAMNADO-7348: remove /preview references

### PR DESCRIPTION
**Pull request by jlgre**
This was the only place in the code base referring to `/preview` - and it wasn't used anywhere, so I just deleted it

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by BrooklynLCodes — APPROVED** [review]
LGTM

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by kjmccauley — APPROVED** [review]

**Pull request merged**
