### PR TITLE
TEAMNADO-7162: update redirects

### PR DESCRIPTION
**Pull request by jlgre**

### CODE REVIEW

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by BrooklynLCodes — APPROVED** [review]

**Comment by BrooklynLCodes** [comment]
Lgtm

**Comment by InsightsDroid** [comment]
## :exclamation: Outdated dependencies error
* Installed version of @redhat-cloud-services/frontend-components-config (5.0.5) is older than required version (6.0.0)

**Review by kjmccauley — APPROVED** [review]

**Pull request merged**
